### ISSUE TITLE
[FeatureRequest] Custom Parameters and their Units

### ISSUE THREAD

**Issue by TheRealFalseReality** [wilsto/pool-monitor-card#29]
**Is your feature request related to a problem? Please describe.**
Somewhat.  A few already open issues include a lower bound of 0, and no negatives, and the ability to rearrange the parameters.

**Describe the solution you'd like**
I really like this card, but I use it for my Aquarium parameters, which share some parameters for a pool, but a few others that do not. 
This includes Ammonia, Phosphate, Nitrate, Nitrite, and Dissolved Oxygen, and probably a few others. Would it be possible to add these parameters? Or perhaps the ability to add custom parameters and their units? It would make the card very flexible!  
I use my own device and EZO probes for salinity, pH and DO and log toxins with number helpers.

**Describe alternatives you've considered**
I'm just not very familiar with creating custom lovelave cards, so I dunno if this is even possible.  To my knowledge, there are no cards directly available for Aquariums, but this is the closest I have seen for my needs, and it is nearly perfect for monitoring toxin ranges at a glance! I'm just using number helpers to log the parameter data and displaying them with graphs, but I think having a range bar would be much better!

**Additional context**

**Comment by wilsto** [comment]
@TheRealFalseReality  I'm creating an Aquarium version of this card. I will close your issue when available with the link. Can you give more info about your specific needs ? thanks

**Comment by TheRealFalseReality** [comment]
Thanks! for your interest! I like this card and use it on my aquariums, good quick visualization on ideal levels! This card is already great for typical aquarium parameters such as Temp., pH, Salinity (or TDS), Calcium, Mag., Alk. And with the most recent update, now with Water Level and Product Volume/weight (I auto dose stuff so this can actually be a useful metric to track, I just go over there and check on the remaining amount manually). Perhaps something for visualize the amount dosed can be useful.

One thing that would make this card all inclusive for aquariums would be to zero out the min and no negative numbers (as there is an existing issue for that). For toxins like Ammonia, Nitrite, Nitrate, Phosphate (which is there but will show negative numbers so I don't currently use Phosphate in this card)  and possibly others.

**Comment by TheRealFalseReality** [comment]
One additional parameter that may be more aquarium related could be dissolved oxygen. I have one reef tank which I measure ORP, and I use your card for that, but I just added a DO sensor to another tank, where ORP is less important.

**Comment by TheRealFalseReality** [comment]
Here is what I am doing so far because you can use a lot of custom stuff now. Another idea would be useful if instead of saying too low in Heatmap mode, could the lower limit be ideal rather than too low? And the opposite could be useful for product weight and volume. If you have a full bottle of product that's auto-dose, the higher limit could be blue and be Ideal rather and Too High. Thanks!

```
type: custom:pool-monitor-card
title: Aquarium Parameters
sensors:
  water_level:
    entity: sensor.aquapi_f2c1e4_dissolved_oxygen_saturation
    name: Dissolved Oxygen
    icon: mdi:gas-cylinder
    setpoint: 100
    step: 15
    min: sensor.marine_dissolved_oxygen_min
    max: sensor.marine_dissolved_oxygen_max
  calcium:
    entity: sensor.marine_amminia
    name: Ammonia
    icon: mdi:bottle-tonic-skull
    mode: heatflow
    setpoint: 4
    step: 1
```
![Screenshot 2024-12-22 120306](https://github.com/user-attachments/assets/6d3caf3c-7b50-40ee-9338-06007472eac8)
