### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GeorgeBark** [wilsto/pool-monitor-card#31]
**Describe the bug**
When the setpoint is overriden with an integer value, even if the step is float, the values shown are ronded.

**To Reproduce**
```yaml
total_chlorine_name: Chlorine
total_chlorine_unit: mg/L
total_chlorine_setpoint: 1
total_chlorine_step: 0.4
```

As shown in the screenshot below, it will round the steps. Even entering 1.0, same behavior

**Expected behavior**
Display the 1 as 1.0 and the steps correctly.

**Screenshots**
![Screenshot 2023-09-16 at 22 01 35](https://github.com/wilsto/pool-monitor-card/assets/7204152/eaf0ea87-3506-45cd-85c3-3860f7b94b90)

![Screenshot 2023-09-16 at 22 01 25](https://github.com/wilsto/pool-monitor-card/assets/7204152/8a2d12ec-686c-461f-bc65-6562ceed04d3)
