### ISSUE TITLE
[BUG] mdi icons mess up compact layout

### ISSUE THREAD

**Issue by nijel** [wilsto/pool-monitor-card#49]
**Describe the bug**

**To Reproduce**
1. Customize icon using mdi tag and use compact display

```yaml
type: custom:pool-monitor-card
temperature: sensor.bazen_temperature
temperature_icon:
  mdi: mdi:pool-thermometer
temperature_name: Voda
compact: true
```

2. Display the card
3. See error

**Expected behavior**
I'd expect labels to be aligned under the icons.

**Screenshots**

![obrazek](https://github.com/user-attachments/assets/eee3a2b8-c7d1-4884-bf96-44b7fd6a970d)

**Environment (please complete the following information):**
 - Pool Monitor Card version: 1.9.0
 - Browser: Firefox 128
 - Browser language: Czech

**Additional context**
The issue only exists in the compact display.
