### ISSUE TITLE
[BUG] Display bar colours don't match the setpoints

### ISSUE THREAD

**Issue by phrak** [wilsto/pool-monitor-card#57]
**Describe the bug**
Display bar colors don't match the setpoints for the Pool Monitor Card.

**Steps to reproduce the behavior:**

1. Add the Pool Monitor Card to your Lovelace dashboard
2. Configure the card with sensors and setpoints
3. Observe the display bars for each sensor

**Expected behavior**
The colors of the display bars should accurately reflect the setpoint ranges defined for each sensor. For example, if a sensor value is within the "normal" range as defined by the setpoints, the bar should display the corresponding "normal" color. 

**Screenshots**
[The screenshot provided shows discrepancies between the display bar colors and what would be expected based on the setpoint values] 
![image](https://github.com/user-attachments/assets/630de5a2-924f-48a5-b644-b942f108addb)

My YAML setpoints are:

- temperature: 27
- ph: 7.5
- orp: 650

**Environment** (please complete the following information):

    Pool Monitor Card version: v2.1.0
    Browser: Any
    Browser language: EN-AU

**Additional context**
The issue appears to be a mismatch between the color display logic and the defined setpoint values. This could be due to:

- Incorrect color mapping in the card's code
- Setpoint ranges not being properly applied to the color logic
- Possible color management issues with the browser or display

This bug impacts the card's primary function of visually representing pool parameters, potentially leading to misinterpretation of sensor data by users.

**Card YAML**

    type: custom:pool-monitor-card
    title: Pool Monitor
    icon: mdi:pool
    sensors:
      temperature:
        name: Temperature
        entity: sensor.hchlor_water_temperature
        unit: °C
        decimals: 1
        icon: mdi:thermometer
        min: 0
        max: 40
      ph:
        name: pH
        entity: sensor.hchlor_ph
        unit: pH
        decimals: 1
        icon: mdi:ph
        min: 6.5
        max: 8.5
      orp:
        name: ORP
        entity: sensor.hchlor_orp_measurement
        unit: mV
        decimals: 0
        icon: mdi:flash
        min: 500
        max: 800
    setpoints:
      temperature:
        value: 27
        step: 1
      ph:
        value: 7.5
        step: 0.2
      orp:
        value: 650
        step: 10
    settings:
      compact_view: false
      show_names: true
      show_labels: true
      show_last_updated: false
      tap_action:
        action: more-info

**Comment by wilsto** [comment]
Hi @phrak,

Thank you for sharing your YAML configuration! I think I’ve pinpointed the issue with your setup. It seems the setpoint and step parameters are not correctly placed—they need to be defined under each individual sensor, not globally. Additionally, the setpoints and settings parameters mentioned don't exist in the documentation, which might be causing some confusion.

Here’s a corrected version of the code that follows the expected structure and ensures the card behaves as intended:

 ```yaml
type: custom:pool-monitor-card
title: Pool Monitor
sensors:
  temperature:
    name: Temperature
    entity: sensor.hchlor_water_temperature
    setpoint : 27
    step: 1
    unit: °C
    decimals: 1
    icon: mdi:thermometer
    min: 0
    max: 40
  ph:
    name: pH
    entity: sensor.hchlor_ph
    setpoint : 7.5
    step: 0.2
    unit: pH
    decimals: 1
    icon: mdi:ph
    min: 6.5
    max: 8.5
  orp:
    name: ORP
    entity: sensor.hchlor_orp_measurement
    setpoint : 650
    step: 10
    unit: mV
    decimals: 0
    icon: mdi:flash
    min: 500
    max: 800
display:
  compact_view: false
  show_names: true
  show_labels: true
  show_last_updated: false
```
    
**How to Optimize Further:**
To make your YAML configuration more concise, you can omit parameters that align with the card's default values. For example, in the temperature sensor, the default setpoint is already 27 and step is 1. Unless you are customizing those defaults, they don’t need to be explicitly stated.

Here’s an optimized version for your configuration, only modifying parameters where defaults need to be overridden:
    
 ```yaml
type: custom:pool-monitor-card
title: Pool Monitor
sensors:
  temperature:
    entity: sensor.hchlor_water_temperature
  ph:
    entity: sensor.hchlor_ph
    setpoint: 7.5
    step: 0.2
  orp:
    entity: sensor.hchlor_orp_measurement
    setpoint: 650
    step: 10
```
    
    
**The Result:**
Using this optimized YAML, the card will still display correctly while reducing unnecessary redundancy. Here’s what it would look like:
    
![image](https://github.com/user-attachments/assets/608536ae-63ae-43e7-a190-5e0b8e9e5439)

**Key Takeaway:**
By leveraging the card’s default values, you can keep your configuration simpler and easier to maintain while focusing on customizations that matter for your setup. Let me know if you need further assistance or adjustments! 😊
